a = int(input("Enter first number: "))
b = int(input("Enter second number: "))

print("Addition =", a + b)
print("Subtraction =", a - b)
print("Multiplication =", a * b)
print("Division =", round(a / b, 2))
print("Floor Division =", a // b)
print("Modulus =", a % b)
print("Exponent =", a ** b)